ALTER TABLE dbo.Advogado
ADD CEP VARCHAR (11) NOT NULL,
Bairro VARCHAR (50) NOT NULL,
Cidade VARCHAR (50) NOT NULL,
Logradouro VARCHAR(100) NOT NULL,
UF VARCHAR (11) NOT NULL,
Biografia VARCHAR (1000) NOT NULL,
Complemento VARCHAR (150) ,
Especializacao VARCHAR (100) NOT NULL;
		
